"""initial_schema

Revision ID: 29bbc2bb9e19
Revises: 
Create Date: 2026-09-16 23:48:00.234067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '29bbc2bb9e19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_event_created', 'audit_logs', ['event', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event'), 'audit_logs', ['event'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='membershiprole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_membership_user_org')
    )
    op.create_index('ix_membership_user_org', 'memberships', ['user_id', 'organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_id'), 'memberships', ['id'], unique=False)
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.alter_column('analysis_results', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('analysis_results', 'result_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('analysis_results', 'data',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('analysis_results', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_analysis_results_project_id'), 'analysis_results', ['project_id'], unique=False)
    op.create_index('ix_result_project_type', 'analysis_results', ['project_id', 'result_type'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'analysis_results', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_results', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('datasets', sa.Column('storage_name', sa.String(length=255), nullable=False))
    op.add_column('datasets', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('datasets', sa.Column('storage_path', sa.String(length=500), nullable=True))
    op.add_column('datasets', sa.Column('row_count', sa.Integer(), nullable=True))
    op.add_column('datasets', sa.Column('column_count', sa.Integer(), nullable=True))
    op.alter_column('datasets', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('datasets', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('datasets', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('datasets', 'uploaded_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_datasets_project_id'), 'datasets', ['project_id'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.create_foreign_key(None, 'datasets', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('datasets', 'file_path')
    op.drop_column('datasets', 'rows')
    op.drop_column('datasets', 'columns')
    op.drop_column('datasets', 'filename')
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'service_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'package_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'amount',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('payments', sa.Column('provider', sa.String(length=50), nullable=False))
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'processed_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.add_column('processing_jobs', sa.Column('job_id', sa.String(length=36), nullable=False))
    op.alter_column('processing_jobs', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('processing_jobs', 'job_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('processing_jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_processing_jobs_job_id'), 'processing_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_processing_jobs_project_id'), 'processing_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'processing_jobs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'external_id')
    op.drop_column('users', 'is_email_verified')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'projects', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.alter_column('projects', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'organization_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'processing_jobs', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_project_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_id'), table_name='processing_jobs')
    op.alter_column('processing_jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('processing_jobs', 'job_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('processing_jobs', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('processing_jobs', 'job_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'])
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=False)
    op.alter_column('payments', 'processed_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('payments', 'provider')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.alter_column('orders', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'amount',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('orders', 'package_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'service_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'idempotency_key')
    op.add_column('datasets', sa.Column('filename', sa.VARCHAR(), nullable=True))
    op.add_column('datasets', sa.Column('columns', sa.INTEGER(), nullable=True))
    op.add_column('datasets', sa.Column('rows', sa.INTEGER(), nullable=True))
    op.add_column('datasets', sa.Column('file_path', sa.VARCHAR(), nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.create_foreign_key(None, 'datasets', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_datasets_project_id'), table_name='datasets')
    op.alter_column('datasets', 'uploaded_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('datasets', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('datasets', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('datasets', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('datasets', 'column_count')
    op.drop_column('datasets', 'row_count')
    op.drop_column('datasets', 'storage_path')
    op.drop_column('datasets', 'original_filename')
    op.drop_column('datasets', 'storage_name')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'analysis_results', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_results', 'projects', ['project_id'], ['id'])
    op.drop_index('ix_result_project_type', table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_project_id'), table_name='analysis_results')
    op.alter_column('analysis_results', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('analysis_results', 'data',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('analysis_results', 'result_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('analysis_results', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_id'), table_name='memberships')
    op.drop_index('ix_membership_user_org', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_event_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
